### ISSUE TITLE
[core] Migrate to from utility-hooks to react-use 

### ISSUE THREAD

**Issue by umidbekkarimov** [superdispatch/ui#83]
See https://github.com/streamich/react-use

**Comment by doniyor2109** [comment]
@umidbekkarimov `utility-hooks` are not fully compatible with `react-use` (.e.g `usePureMemo`). Should we create `usePureMemo` for locally?

**Comment by umidbekkarimov** [comment]
@doniyor2109 I will take care of this task, work on your roadmap items :) or migrate your tests to cypress :)
