### ISSUE TITLE
[ui] Wrong Autocomplete height when filled.

### ISSUE THREAD

**Issue by doniyor2109** [superdispatch/ui#92]
Autocomplete height is 34px when filled. It should be 32px like other Text Fields.

https://d.pr/free/i/6Gdhq2

**Comment by umidbekkarimov** [comment]
@doniyor2109 I can't reproduce it in https://ui.superdispatch.org

**Comment by doniyor2109** [comment]
It was reported by Lucia. I will try reproduce it.

**Comment by umidbekkarimov** [comment]
@doniyor2109 I checked and found that it's because of the close button in the chip. In sd/ui it has no padding, but in the app it has 4px. If there are no theme overrides, update to the latest version of sd/ui and mui will fix the problem.
